stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: dganitch/alpine-smarter-v2
      pushRemote: true
      registry: index.docker.io
timeout: 60
