version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t alpine-smarter:1.5 .
      - docker tag alpine-smarter:1.5  aws-your-account.dkr.ecr.us-west-2.amazonaws.com/alpine-smarter:1.5
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push aws-your-account.dkr.ecr.us-west-2.amazonaws.com/alpine-smarter
